# This is a simple configuration to test OSC library
image: python:3.6

pipelines:
  default:
    - step:
        script:
            # run tests
          - python -m unittest discover -s ./osc/test -p 'test_*.py'